//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 03:33:43 PM PDT 
//


package parsers.PMC;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}element-citation"/>
 *         &lt;element ref="{}mixed-citation"/>
 *         &lt;element ref="{}nlm-citation"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "elementCitationOrMixedCitationOrNlmCitation"
})
@XmlRootElement(name = "citation-alternatives")
public class CitationAlternatives {

    @XmlElements({
        @XmlElement(name = "element-citation", type = ElementCitation.class),
        @XmlElement(name = "mixed-citation", type = MixedCitation.class),
        @XmlElement(name = "nlm-citation", type = NlmCitation.class)
    })
    protected List<Object> elementCitationOrMixedCitationOrNlmCitation;

    /**
     * Gets the value of the elementCitationOrMixedCitationOrNlmCitation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elementCitationOrMixedCitationOrNlmCitation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElementCitationOrMixedCitationOrNlmCitation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElementCitation }
     * {@link MixedCitation }
     * {@link NlmCitation }
     * 
     * 
     */
    public List<Object> getElementCitationOrMixedCitationOrNlmCitation() {
        if (elementCitationOrMixedCitationOrNlmCitation == null) {
            elementCitationOrMixedCitationOrNlmCitation = new ArrayList<Object>();
        }
        return this.elementCitationOrMixedCitationOrNlmCitation;
    }

}
