//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 03:33:43 PM PDT 
//


package parsers.PMC;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}journal-id" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}journal-title-group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}contrib-group"/>
 *           &lt;element ref="{}aff"/>
 *           &lt;element ref="{}aff-alternatives"/>
 *         &lt;/choice>
 *         &lt;element ref="{}issn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}issn-l" minOccurs="0"/>
 *         &lt;element ref="{}isbn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}publisher" minOccurs="0"/>
 *         &lt;element ref="{}notes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}self-uri" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}custom-meta-group" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journalId",
    "journalTitleGroup",
        "journalTitle",
    "contribGroupOrAffOrAffAlternatives",
    "issn",
    "issnL",
    "isbn",
    "publisher",
    "notes",
    "selfUri",
    "customMetaGroup"
})
@XmlRootElement(name = "journal-meta")
public class JournalMeta {

    @XmlElement(name = "journal-id")
    protected List<JournalId> journalId;
    @XmlElement(name = "journal-title-group")
    protected List<JournalTitleGroup> journalTitleGroup;
    @XmlElement(name = "journal-title")
    protected JournalTitle journalTitle;
    @XmlElements({
        @XmlElement(name = "contrib-group", type = ContribGroup.class),
        @XmlElement(name = "aff", type = Aff.class),
        @XmlElement(name = "aff-alternatives", type = AffAlternatives.class)
    })
    protected List<Object> contribGroupOrAffOrAffAlternatives;
    protected List<Issn> issn;
    @XmlElement(name = "issn-l")
    protected IssnL issnL;
    protected List<Isbn> isbn;
    protected Publisher publisher;
    protected List<Notes> notes;
    @XmlElement(name = "self-uri")
    protected List<SelfUri> selfUri;
    @XmlElement(name = "custom-meta-group")
    protected CustomMetaGroup customMetaGroup;

    /**
     * Gets the value of the journalId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journalId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJournalId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalId }
     * 
     * 
     */
    public List<JournalId> getJournalId() {
        if (journalId == null) {
            journalId = new ArrayList<JournalId>();
        }
        return this.journalId;
    }

    /**
     * Gets the value of the journalTitleGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journalTitleGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJournalTitleGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalTitleGroup }
     * 
     * 
     */
    public List<JournalTitleGroup> getJournalTitleGroup() {
        if (journalTitleGroup == null) {
            journalTitleGroup = new ArrayList<JournalTitleGroup>();
        }
        return this.journalTitleGroup;
    }

    public JournalTitle getJournalTitleDeprec(){
        return journalTitle;
    }

    /**
     * Gets the value of the contribGroupOrAffOrAffAlternatives property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contribGroupOrAffOrAffAlternatives property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContribGroupOrAffOrAffAlternatives().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContribGroup }
     * {@link Aff }
     * {@link AffAlternatives }
     * 
     * 
     */
    public List<Object> getContribGroupOrAffOrAffAlternatives() {
        if (contribGroupOrAffOrAffAlternatives == null) {
            contribGroupOrAffOrAffAlternatives = new ArrayList<Object>();
        }
        return this.contribGroupOrAffOrAffAlternatives;
    }

    /**
     * Gets the value of the issn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Issn }
     * 
     * 
     */
    public List<Issn> getIssn() {
        if (issn == null) {
            issn = new ArrayList<Issn>();
        }
        return this.issn;
    }

    /**
     * Gets the value of the issnL property.
     * 
     * @return
     *     possible object is
     *     {@link IssnL }
     *     
     */
    public IssnL getIssnL() {
        return issnL;
    }

    /**
     * Sets the value of the issnL property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssnL }
     *     
     */
    public void setIssnL(IssnL value) {
        this.issnL = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isbn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsbn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Isbn }
     * 
     * 
     */
    public List<Isbn> getIsbn() {
        if (isbn == null) {
            isbn = new ArrayList<Isbn>();
        }
        return this.isbn;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link Publisher }
     *     
     */
    public Publisher getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publisher }
     *     
     */
    public void setPublisher(Publisher value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Notes }
     * 
     * 
     */
    public List<Notes> getNotes() {
        if (notes == null) {
            notes = new ArrayList<Notes>();
        }
        return this.notes;
    }

    /**
     * Gets the value of the selfUri property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selfUri property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelfUri().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelfUri }
     * 
     * 
     */
    public List<SelfUri> getSelfUri() {
        if (selfUri == null) {
            selfUri = new ArrayList<SelfUri>();
        }
        return this.selfUri;
    }

    /**
     * Gets the value of the customMetaGroup property.
     * 
     * @return
     *     possible object is
     *     {@link CustomMetaGroup }
     *     
     */
    public CustomMetaGroup getCustomMetaGroup() {
        return customMetaGroup;
    }

    /**
     * Sets the value of the customMetaGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomMetaGroup }
     *     
     */
    public void setCustomMetaGroup(CustomMetaGroup value) {
        this.customMetaGroup = value;
    }

}
