//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 03:33:43 PM PDT 
//


package parsers.PMC;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}inline-supplementary-material"/>
 *         &lt;element ref="{}related-article"/>
 *         &lt;element ref="{}related-object"/>
 *         &lt;element ref="{}hr"/>
 *         &lt;element ref="{}break"/>
 *         &lt;element ref="{}string-date"/>
 *         &lt;element ref="{}bold"/>
 *         &lt;element ref="{}italic"/>
 *         &lt;element ref="{}monospace"/>
 *         &lt;element ref="{}overline"/>
 *         &lt;element ref="{}overline-start"/>
 *         &lt;element ref="{}overline-end"/>
 *         &lt;element ref="{}roman"/>
 *         &lt;element ref="{}sans-serif"/>
 *         &lt;element ref="{}sc"/>
 *         &lt;element ref="{}strike"/>
 *         &lt;element ref="{}underline"/>
 *         &lt;element ref="{}underline-start"/>
 *         &lt;element ref="{}underline-end"/>
 *         &lt;element ref="{}alternatives"/>
 *         &lt;element ref="{}inline-graphic"/>
 *         &lt;element ref="{}private-char"/>
 *         &lt;element ref="{}chem-struct"/>
 *         &lt;element ref="{}inline-formula"/>
 *         &lt;element ref="{}label"/>
 *         &lt;element ref="{}tex-math"/>
 *         &lt;element ref="{http://www.w3.org/1998/Math/MathML}math"/>
 *         &lt;element ref="{}abbrev"/>
 *         &lt;element ref="{}milestone-end"/>
 *         &lt;element ref="{}milestone-start"/>
 *         &lt;element ref="{}named-content"/>
 *         &lt;element ref="{}styled-content"/>
 *         &lt;element ref="{}annotation"/>
 *         &lt;element ref="{}article-title"/>
 *         &lt;element ref="{}chapter-title"/>
 *         &lt;element ref="{}collab"/>
 *         &lt;element ref="{}collab-alternatives"/>
 *         &lt;element ref="{}comment"/>
 *         &lt;element ref="{}conf-date"/>
 *         &lt;element ref="{}conf-loc"/>
 *         &lt;element ref="{}conf-name"/>
 *         &lt;element ref="{}conf-sponsor"/>
 *         &lt;element ref="{}date"/>
 *         &lt;element ref="{}date-in-citation"/>
 *         &lt;element ref="{}day"/>
 *         &lt;element ref="{}edition"/>
 *         &lt;element ref="{}email"/>
 *         &lt;element ref="{}elocation-id"/>
 *         &lt;element ref="{}etal"/>
 *         &lt;element ref="{}ext-link"/>
 *         &lt;element ref="{}fpage"/>
 *         &lt;element ref="{}gov"/>
 *         &lt;element ref="{}institution"/>
 *         &lt;element ref="{}isbn"/>
 *         &lt;element ref="{}issn"/>
 *         &lt;element ref="{}issn-l"/>
 *         &lt;element ref="{}issue"/>
 *         &lt;element ref="{}issue-id"/>
 *         &lt;element ref="{}issue-part"/>
 *         &lt;element ref="{}issue-title"/>
 *         &lt;element ref="{}lpage"/>
 *         &lt;element ref="{}month"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}name-alternatives"/>
 *         &lt;element ref="{}object-id"/>
 *         &lt;element ref="{}page-range"/>
 *         &lt;element ref="{}part-title"/>
 *         &lt;element ref="{}patent"/>
 *         &lt;element ref="{}person-group"/>
 *         &lt;element ref="{}pub-id"/>
 *         &lt;element ref="{}publisher-loc"/>
 *         &lt;element ref="{}publisher-name"/>
 *         &lt;element ref="{}role"/>
 *         &lt;element ref="{}season"/>
 *         &lt;element ref="{}series"/>
 *         &lt;element ref="{}size"/>
 *         &lt;element ref="{}source"/>
 *         &lt;element ref="{}std"/>
 *         &lt;element ref="{}string-name"/>
 *         &lt;element ref="{}supplement"/>
 *         &lt;element ref="{}trans-source"/>
 *         &lt;element ref="{}trans-title"/>
 *         &lt;element ref="{}uri"/>
 *         &lt;element ref="{}volume"/>
 *         &lt;element ref="{}volume-id"/>
 *         &lt;element ref="{}volume-series"/>
 *         &lt;element ref="{}year"/>
 *         &lt;element ref="{}fn"/>
 *         &lt;element ref="{}target"/>
 *         &lt;element ref="{}xref"/>
 *         &lt;element ref="{}sub"/>
 *         &lt;element ref="{}sup"/>
 *         &lt;element ref="{}x"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="link-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ext-link-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="source-id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="source-id-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="source-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="document-id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="document-id-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="document-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="object-id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="object-id-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="object-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="content-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="specific-use" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}type"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}role"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}title"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}show"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}actuate"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "related-object")
public class RelatedObject {

    @XmlElementRefs({
        @XmlElementRef(name = "object-id", type = ObjectId.class, required = false),
        @XmlElementRef(name = "size", type = Size.class, required = false),
        @XmlElementRef(name = "x", type = X.class, required = false),
        @XmlElementRef(name = "publisher-name", type = PublisherName.class, required = false),
        @XmlElementRef(name = "pub-id", type = PubId.class, required = false),
        @XmlElementRef(name = "institution", type = Institution.class, required = false),
        @XmlElementRef(name = "part-title", type = PartTitle.class, required = false),
        @XmlElementRef(name = "collab", type = Collab.class, required = false),
        @XmlElementRef(name = "string-name", type = StringName.class, required = false),
        @XmlElementRef(name = "collab-alternatives", type = CollabAlternatives.class, required = false),
        @XmlElementRef(name = "conf-name", type = ConfName.class, required = false),
        @XmlElementRef(name = "underline-end", type = UnderlineEnd.class, required = false),
        @XmlElementRef(name = "issue-title", type = IssueTitle.class, required = false),
        @XmlElementRef(name = "styled-content", type = StyledContent.class, required = false),
        @XmlElementRef(name = "volume-series", type = VolumeSeries.class, required = false),
        @XmlElementRef(name = "date-in-citation", type = DateInCitation.class, required = false),
        @XmlElementRef(name = "name-alternatives", type = NameAlternatives.class, required = false),
        @XmlElementRef(name = "abbrev", type = Abbrev.class, required = false),
        @XmlElementRef(name = "sup", type = Sup.class, required = false),
        @XmlElementRef(name = "conf-loc", type = ConfLoc.class, required = false),
        @XmlElementRef(name = "ext-link", type = ExtLink.class, required = false),
        @XmlElementRef(name = "underline", type = Underline.class, required = false),
        @XmlElementRef(name = "related-article", type = RelatedArticle.class, required = false),
        @XmlElementRef(name = "label", type = Label.class, required = false),
        @XmlElementRef(name = "tex-math", type = TexMath.class, required = false),
        @XmlElementRef(name = "volume-id", type = VolumeId.class, required = false),
        @XmlElementRef(name = "chem-struct", type = ChemStruct.class, required = false),
        @XmlElementRef(name = "month", type = Month.class, required = false),
        @XmlElementRef(name = "elocation-id", type = ElocationId.class, required = false),
        @XmlElementRef(name = "comment", type = Comment.class, required = false),
        @XmlElementRef(name = "isbn", type = Isbn.class, required = false),
        @XmlElementRef(name = "season", type = Season.class, required = false),
        @XmlElementRef(name = "issue-part", type = IssuePart.class, required = false),
        @XmlElementRef(name = "chapter-title", type = ChapterTitle.class, required = false),
        @XmlElementRef(name = "conf-sponsor", type = ConfSponsor.class, required = false),
        @XmlElementRef(name = "lpage", type = Lpage.class, required = false),
        @XmlElementRef(name = "break", type = Break.class, required = false),
        @XmlElementRef(name = "inline-formula", type = InlineFormula.class, required = false),
        @XmlElementRef(name = "year", type = Year.class, required = false),
        @XmlElementRef(name = "page-range", type = PageRange.class, required = false),
        @XmlElementRef(name = "name", type = Name.class, required = false),
        @XmlElementRef(name = "milestone-start", type = MilestoneStart.class, required = false),
        @XmlElementRef(name = "named-content", type = NamedContent.class, required = false),
        @XmlElementRef(name = "xref", type = Xref.class, required = false),
        @XmlElementRef(name = "role", type = Role.class, required = false),
        @XmlElementRef(name = "article-title", type = ArticleTitle.class, required = false),
        @XmlElementRef(name = "string-date", type = StringDate.class, required = false),
        @XmlElementRef(name = "target", type = Target.class, required = false),
        @XmlElementRef(name = "fpage", type = Fpage.class, required = false),
        @XmlElementRef(name = "gov", type = Gov.class, required = false),
        @XmlElementRef(name = "roman", type = Roman.class, required = false),
        @XmlElementRef(name = "issn", type = Issn.class, required = false),
        @XmlElementRef(name = "overline-start", type = OverlineStart.class, required = false),
        @XmlElementRef(name = "bold", type = Bold.class, required = false),
        @XmlElementRef(name = "strike", type = Strike.class, required = false),
        @XmlElementRef(name = "publisher-loc", type = PublisherLoc.class, required = false),
        @XmlElementRef(name = "overline", type = Overline.class, required = false),
        @XmlElementRef(name = "issue", type = Issue.class, required = false),
        @XmlElementRef(name = "issue-id", type = IssueId.class, required = false),
        @XmlElementRef(name = "sans-serif", type = SansSerif.class, required = false),
        @XmlElementRef(name = "milestone-end", type = MilestoneEnd.class, required = false),
        @XmlElementRef(name = "issn-l", type = IssnL.class, required = false),
        @XmlElementRef(name = "math", namespace = "http://www.w3.org/1998/Math/MathML", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "series", type = Series.class, required = false),
        @XmlElementRef(name = "supplement", type = Supplement.class, required = false),
        @XmlElementRef(name = "private-char", type = PrivateChar.class, required = false),
        @XmlElementRef(name = "volume", type = Volume.class, required = false),
        @XmlElementRef(name = "day", type = Day.class, required = false),
        @XmlElementRef(name = "source", type = Source.class, required = false),
        @XmlElementRef(name = "inline-graphic", type = InlineGraphic.class, required = false),
        @XmlElementRef(name = "underline-start", type = UnderlineStart.class, required = false),
        @XmlElementRef(name = "etal", type = Etal.class, required = false),
        @XmlElementRef(name = "hr", type = Hr.class, required = false),
        @XmlElementRef(name = "inline-supplementary-material", type = InlineSupplementaryMaterial.class, required = false),
        @XmlElementRef(name = "monospace", type = Monospace.class, required = false),
        @XmlElementRef(name = "related-object", type = RelatedObject.class, required = false),
        @XmlElementRef(name = "fn", type = Fn.class, required = false),
        @XmlElementRef(name = "alternatives", type = Alternatives.class, required = false),
        @XmlElementRef(name = "patent", type = Patent.class, required = false),
        @XmlElementRef(name = "trans-title", type = TransTitle.class, required = false),
        @XmlElementRef(name = "date", type = Date.class, required = false),
        @XmlElementRef(name = "email", type = Email.class, required = false),
        @XmlElementRef(name = "italic", type = Italic.class, required = false),
        @XmlElementRef(name = "sc", type = Sc.class, required = false),
        @XmlElementRef(name = "trans-source", type = TransSource.class, required = false),
        @XmlElementRef(name = "std", type = Std.class, required = false),
        @XmlElementRef(name = "conf-date", type = ConfDate.class, required = false),
        @XmlElementRef(name = "person-group", type = PersonGroup.class, required = false),
        @XmlElementRef(name = "annotation", type = Annotation.class, required = false),
        @XmlElementRef(name = "sub", type = Sub.class, required = false),
        @XmlElementRef(name = "edition", type = Edition.class, required = false),
        @XmlElementRef(name = "overline-end", type = OverlineEnd.class, required = false),
        @XmlElementRef(name = "uri", type = Uri.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "link-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String linkType;
    @XmlAttribute(name = "ext-link-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String extLinkType;
    @XmlAttribute(name = "source-id")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourceId;
    @XmlAttribute(name = "source-id-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourceIdType;
    @XmlAttribute(name = "source-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourceType;
    @XmlAttribute(name = "document-id")
    @XmlSchemaType(name = "anySimpleType")
    protected String documentId;
    @XmlAttribute(name = "document-id-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String documentIdType;
    @XmlAttribute(name = "document-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String documentType;
    @XmlAttribute(name = "object-id")
    @XmlSchemaType(name = "anySimpleType")
    protected String objectId;
    @XmlAttribute(name = "object-id-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String objectIdType;
    @XmlAttribute(name = "object-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String objectType;
    @XmlAttribute(name = "content-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String contentType;
    @XmlAttribute(name = "specific-use")
    @XmlSchemaType(name = "anySimpleType")
    protected String specificUse;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String lang;
    @XmlAttribute(name = "type", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "href", namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anySimpleType")
    protected String href;
    @XmlAttribute(name = "role", namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anySimpleType")
    protected String role;
    @XmlAttribute(name = "title", namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anySimpleType")
    protected String title;
    @XmlAttribute(name = "show", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String show;
    @XmlAttribute(name = "actuate", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String actuate;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectId }
     * {@link Size }
     * {@link PublisherName }
     * {@link X }
     * {@link PubId }
     * {@link Institution }
     * {@link PartTitle }
     * {@link Collab }
     * {@link String }
     * {@link StringName }
     * {@link CollabAlternatives }
     * {@link ConfName }
     * {@link UnderlineEnd }
     * {@link IssueTitle }
     * {@link StyledContent }
     * {@link DateInCitation }
     * {@link VolumeSeries }
     * {@link Abbrev }
     * {@link NameAlternatives }
     * {@link ConfLoc }
     * {@link Sup }
     * {@link RelatedArticle }
     * {@link Underline }
     * {@link ExtLink }
     * {@link Label }
     * {@link TexMath }
     * {@link ChemStruct }
     * {@link VolumeId }
     * {@link Month }
     * {@link ElocationId }
     * {@link Comment }
     * {@link Isbn }
     * {@link Season }
     * {@link ChapterTitle }
     * {@link IssuePart }
     * {@link ConfSponsor }
     * {@link Break }
     * {@link Lpage }
     * {@link InlineFormula }
     * {@link Name }
     * {@link PageRange }
     * {@link Year }
     * {@link MilestoneStart }
     * {@link NamedContent }
     * {@link ArticleTitle }
     * {@link Role }
     * {@link Xref }
     * {@link StringDate }
     * {@link Target }
     * {@link Fpage }
     * {@link Gov }
     * {@link Roman }
     * {@link Issn }
     * {@link OverlineStart }
     * {@link Bold }
     * {@link Strike }
     * {@link PublisherLoc }
     * {@link Overline }
     * {@link Issue }
     * {@link MilestoneEnd }
     * {@link SansSerif }
     * {@link IssueId }
     * {@link JAXBElement }{@code <}{@link MathType }{@code >}
     * {@link IssnL }
     * {@link Series }
     * {@link Supplement }
     * {@link PrivateChar }
     * {@link Volume }
     * {@link Day }
     * {@link Source }
     * {@link UnderlineStart }
     * {@link InlineGraphic }
     * {@link Hr }
     * {@link Etal }
     * {@link Monospace }
     * {@link InlineSupplementaryMaterial }
     * {@link RelatedObject }
     * {@link Alternatives }
     * {@link Fn }
     * {@link Patent }
     * {@link Email }
     * {@link Date }
     * {@link TransTitle }
     * {@link Italic }
     * {@link Sc }
     * {@link TransSource }
     * {@link Std }
     * {@link ConfDate }
     * {@link PersonGroup }
     * {@link Annotation }
     * {@link Sub }
     * {@link Edition }
     * {@link OverlineEnd }
     * {@link Uri }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the linkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkType() {
        return linkType;
    }

    /**
     * Sets the value of the linkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkType(String value) {
        this.linkType = value;
    }

    /**
     * Gets the value of the extLinkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtLinkType() {
        return extLinkType;
    }

    /**
     * Sets the value of the extLinkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtLinkType(String value) {
        this.extLinkType = value;
    }

    /**
     * Gets the value of the sourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * Sets the value of the sourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceId(String value) {
        this.sourceId = value;
    }

    /**
     * Gets the value of the sourceIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceIdType() {
        return sourceIdType;
    }

    /**
     * Sets the value of the sourceIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceIdType(String value) {
        this.sourceIdType = value;
    }

    /**
     * Gets the value of the sourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * Sets the value of the sourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceType(String value) {
        this.sourceType = value;
    }

    /**
     * Gets the value of the documentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentId(String value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the documentIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentIdType() {
        return documentIdType;
    }

    /**
     * Sets the value of the documentIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentIdType(String value) {
        this.documentIdType = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the objectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectId(String value) {
        this.objectId = value;
    }

    /**
     * Gets the value of the objectIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectIdType() {
        return objectIdType;
    }

    /**
     * Sets the value of the objectIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectIdType(String value) {
        this.objectIdType = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectType(String value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the specificUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificUse() {
        return specificUse;
    }

    /**
     * Sets the value of the specificUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificUse(String value) {
        this.specificUse = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the show property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShow(String value) {
        this.show = value;
    }

    /**
     * Gets the value of the actuate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActuate(String value) {
        this.actuate = value;
    }

}
