//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 10:14:53 AM PDT 
//


package parsers.medline;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journal",
    "articleTitle",
    "paginationOrELocationID",
    "_abstract",
    "authorList"
})
@XmlRootElement(name = "Article")
public class Article {

    @XmlElement(name = "Journal", required = true)
    protected Journal journal;
    @XmlElement(name = "ArticleTitle", required = true)
    protected String articleTitle;
    @XmlElements({
        @XmlElement(name = "ELocationID", required = true, type = ELocationID.class)
    })
    protected List<Object> paginationOrELocationID;
    @XmlElement(name = "Abstract")
    protected Abstract _abstract;
    @XmlElement(name = "AuthorList")
    protected AuthorList authorList;

    /**
     * Gets the value of the journal property.
     *
     * @return
     *     possible object is
     *     {@link Journal }
     *
     */
    public Journal getJournal() {
        return journal;
    }

    /**
     * Sets the value of the journal property.
     *
     * @param value
     *     allowed object is
     *     {@link Journal }
     *
     */
    public void setJournal(Journal value) {
        this.journal = value;
    }

    /**
     * Gets the value of the articleTitle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * Sets the value of the articleTitle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setArticleTitle(String value) {
        this.articleTitle = value;
    }

    /**
     * Gets the value of the paginationOrELocationID property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paginationOrELocationID property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaginationOrELocationID().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link parsers.medline.Pagination }
     * {@link parsers.medline.ELocationID }
     *
     *
     */
    public List<Object> getPaginationOrELocationID() {
        if (paginationOrELocationID == null) {
            paginationOrELocationID = new ArrayList<Object>();
        }
        return this.paginationOrELocationID;
    }

    /**
     * Gets the value of the abstract property.
     *
     * @return
     *     possible object is
     *     {@link parsers.medline.Abstract }
     *
     */
    public Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     *
     * @param value
     *     allowed object is
     *     {@link parsers.medline.Abstract }
     *
     */
    public void setAbstract(Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the authorList property.
     *
     * @return
     *     possible object is
     *     {@link parsers.medline.AuthorList }
     *
     */
    public AuthorList getAuthorList() {
        return authorList;
    }

    /**
     * Sets the value of the authorList property.
     *
     * @param value
     *     allowed object is
     *     {@link parsers.medline.AuthorList }
     *
     */
    public void setAuthorList(AuthorList value) {
        this.authorList = value;
    }

}
