//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 10:14:53 AM PDT 
//


package parsers.medline;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pmid",
    "dateCreated",
    "dateRevised",
    "article",
    "chemicalList",
    "supplMeshList",
    "citationSubset",
    "geneSymbolList",
    "meshHeadingList",
    "numberOfReferences",
})
@XmlRootElement(name = "MedlineCitation")
public class MedlineCitation {

    @XmlAttribute(name = "VersionDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String versionDate;
    @XmlElement(name = "PMID", required = true)
    protected PMID pmid;
    @XmlElement(name = "DateCreated", required = true)
    protected DateCreated dateCreated;
    @XmlElement(name = "DateRevised")
    protected DateRevised dateRevised;
    @XmlElement(name = "Article", required = true)
    protected Article article;
    @XmlElement(name = "ChemicalList")
    protected ChemicalList chemicalList;
    @XmlElement(name = "SupplMeshList")
    protected SupplMeshList supplMeshList;
    @XmlElement(name = "CitationSubset")
    protected List<CitationSubset> citationSubset;
    @XmlElement(name = "GeneSymbolList")
    protected GeneSymbolList geneSymbolList;
    @XmlElement(name = "MeshHeadingList")
    protected MeshHeadingList meshHeadingList;
    @XmlElement(name = "NumberOfReferences")
    protected String numberOfReferences;

    /**
     * Gets the value of the versionDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersionDate() {
        return versionDate;
    }

    /**
     * Sets the value of the versionDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersionDate(String value) {
        this.versionDate = value;
    }

    /**
     * Gets the value of the pmid property.
     *
     * @return
     *     possible object is
     *     {@link PMID }
     *
     */
    public PMID getPMID() {
        return pmid;
    }

    /**
     * Sets the value of the pmid property.
     *
     * @param value
     *     allowed object is
     *     {@link PMID }
     *
     */
    public void setPMID(PMID value) {
        this.pmid = value;
    }

    /**
     * Gets the value of the dateCreated property.
     *
     * @return
     *     possible object is
     *     {@link DateCreated }
     *
     */
    public DateCreated getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     *
     * @param value
     *     allowed object is
     *     {@link DateCreated }
     *
     */
    public void setDateCreated(DateCreated value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the dateRevised property.
     *
     * @return
     *     possible object is
     *     {@link parsers.medline.DateRevised }
     *
     */
    public DateRevised getDateRevised() {
        return dateRevised;
    }

    /**
     * Sets the value of the dateRevised property.
     *
     * @param value
     *     allowed object is
     *     {@link parsers.medline.DateRevised }
     *
     */
    public void setDateRevised(DateRevised value) {
        this.dateRevised = value;
    }

    /**
     * Gets the value of the article property.
     *
     * @return
     *     possible object is
     *     {@link Article }
     *
     */
    public Article getArticle() {
        return article;
    }

    /**
     * Sets the value of the article property.
     *
     * @param value
     *     allowed object is
     *     {@link Article }
     *
     */
    public void setArticle(Article value) {
        this.article = value;
    }

    /**
     * Gets the value of the chemicalList property.
     *
     * @return
     *     possible object is
     *     {@link ChemicalList }
     *
     */
    public ChemicalList getChemicalList() {
        return chemicalList;
    }

    /**
     * Sets the value of the chemicalList property.
     *
     * @param value
     *     allowed object is
     *     {@link ChemicalList }
     *
     */
    public void setChemicalList(ChemicalList value) {
        this.chemicalList = value;
    }

    /**
     * Gets the value of the supplMeshList property.
     *
     * @return
     *     possible object is
     *     {@link parsers.medline.SupplMeshList }
     *
     */
    public SupplMeshList getSupplMeshList() {
        return supplMeshList;
    }

    /**
     * Sets the value of the supplMeshList property.
     *
     * @param value
     *     allowed object is
     *     {@link parsers.medline.SupplMeshList }
     *
     */
    public void setSupplMeshList(SupplMeshList value) {
        this.supplMeshList = value;
    }

    /**
     * Gets the value of the citationSubset property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citationSubset property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitationSubset().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitationSubset }
     *
     *
     */
    public List<CitationSubset> getCitationSubset() {
        if (citationSubset == null) {
            citationSubset = new ArrayList<CitationSubset>();
        }
        return this.citationSubset;
    }

    /**
     * Gets the value of the geneSymbolList property.
     *
     * @return
     *     possible object is
     *     {@link GeneSymbolList }
     *
     */
    public GeneSymbolList getGeneSymbolList() {
        return geneSymbolList;
    }

    /**
     * Sets the value of the geneSymbolList property.
     *
     * @param value
     *     allowed object is
     *     {@link GeneSymbolList }
     *
     */
    public void setGeneSymbolList(GeneSymbolList value) {
        this.geneSymbolList = value;
    }

    /**
     * Gets the value of the meshHeadingList property.
     *
     * @return
     *     possible object is
     *     {@link parsers.medline.MeshHeadingList }
     *
     */
    public MeshHeadingList getMeshHeadingList() {
        return meshHeadingList;
    }

    /**
     * Sets the value of the meshHeadingList property.
     *
     * @param value
     *     allowed object is
     *     {@link parsers.medline.MeshHeadingList }
     *
     */
    public void setMeshHeadingList(MeshHeadingList value) {
        this.meshHeadingList = value;
    }

    /**
     * Gets the value of the numberOfReferences property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNumberOfReferences() {
        return numberOfReferences;
    }

    /**
     * Sets the value of the numberOfReferences property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNumberOfReferences(String value) {
        this.numberOfReferences = value;
    }

}
