//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 10:14:53 AM PDT 
//


package parsers.medline;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nlm.parsers.medline package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nlm.parsers.medline
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link parsers.medline.MedlineCitationSet }
     *
     */
    public MedlineCitationSet createMedlineCitationSet() {
        return new MedlineCitationSet();
    }

    /**
     * Create an instance of {@link AbstractText }
     *
     */
    public AbstractText createAbstractText() {
        return new AbstractText();
    }

    /**
     * Create an instance of {@link Chemical }
     *
     */
    public Chemical createChemical() {
        return new Chemical();
    }

    /**
     * Create an instance of {@link parsers.medline.LastName }
     *
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link parsers.medline.Month }
     *
     */
    public Month createMonth() {
        return new Month();
    }

    /**
     * Create an instance of {@link parsers.medline.PersonalNameSubjectList }
     *
     */
    public PersonalNameSubjectList createPersonalNameSubjectList() {
        return new PersonalNameSubjectList();
    }

    /**
     * Create an instance of {@link parsers.medline.PersonalNameSubject }
     *
     */
    public PersonalNameSubject createPersonalNameSubject() {
        return new PersonalNameSubject();
    }


    /**
     * Create an instance of {@link MedlineCitation }
     *
     */
    public MedlineCitation createMedlineCitation() {
        return new MedlineCitation();
    }

    /**
     * Create an instance of {@link parsers.medline.PMID }
     *
     */
    public PMID createPMID() {
        return new PMID();
    }

    /**
     * Create an instance of {@link parsers.medline.DateCreated }
     *
     */
    public DateCreated createDateCreated() {
        return new DateCreated();
    }

    /**
     * Create an instance of {@link parsers.medline.DateRevised }
     *
     */
    public DateRevised createDateRevised() {
        return new DateRevised();
    }

    /**
     * Create an instance of {@link parsers.medline.Article }
     *
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link ChemicalList }
     *
     */
    public ChemicalList createChemicalList() {
        return new ChemicalList();
    }

    /**
     * Create an instance of {@link SupplMeshList }
     *
     */
    public SupplMeshList createSupplMeshList() {
        return new SupplMeshList();
    }

    /**
     * Create an instance of {@link parsers.medline.CitationSubset }
     *
     */
    public CitationSubset createCitationSubset() {
        return new CitationSubset();
    }


    /**
     * Create an instance of {@link GeneSymbolList }
     *
     */
    public GeneSymbolList createGeneSymbolList() {
        return new GeneSymbolList();
    }

    /**
     * Create an instance of {@link parsers.medline.MeshHeadingList }
     *
     */
    public MeshHeadingList createMeshHeadingList() {
        return new MeshHeadingList();
    }


    /**
     * Create an instance of {@link Journal }
     *
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link ISSN }
     *
     */
    public ISSN createISSN() {
        return new ISSN();
    }

    /**
     * Create an instance of {@link parsers.medline.JournalIssue }
     *
     */
    public JournalIssue createJournalIssue() {
        return new JournalIssue();
    }

    /**
     * Create an instance of {@link parsers.medline.ForeName }
     *
     */
    public ForeName createForeName() {
        return new ForeName();
    }

    /**
     * Create an instance of {@link parsers.medline.Initials }
     *
     */
    public Initials createInitials() {
        return new Initials();
    }

    /**
     * Create an instance of {@link Suffix }
     *
     */
    public Suffix createSuffix() {
        return new Suffix();
    }



    /**
     * Create an instance of {@link DescriptorName }
     *
     */
    public DescriptorName createDescriptorName() {
        return new DescriptorName();
    }


    /**
     * Create an instance of {@link PubDate }
     *
     */
    public PubDate createPubDate() {
        return new PubDate();
    }

    /**
     * Create an instance of {@link parsers.medline.Year }
     *
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link Day }
     *
     */
    public Day createDay() {
        return new Day();
    }

    /**
     * Create an instance of {@link parsers.medline.ELocationID }
     *
     */
    public ELocationID createELocationID() {
        return new ELocationID();
    }

    /**
     * Create an instance of {@link DeleteCitation }
     *
     */
    public DeleteCitation createDeleteCitation() {
        return new DeleteCitation();
    }

    /**
     * Create an instance of {@link parsers.medline.Author }
     *
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link CollectiveName }
     *
     */
    public CollectiveName createCollectiveName() {
        return new CollectiveName();
    }

    /**
     * Create an instance of {@link AuthorList }
     *
     */
    public AuthorList createAuthorList() {
        return new AuthorList();
    }

    /**
     * Create an instance of {@link GeneSymbol }
     *
     */
    public GeneSymbol createGeneSymbol() {
        return new GeneSymbol();
    }

    /**
     * Create an instance of {@link parsers.medline.SupplMeshName }
     *
     */
    public SupplMeshName createSupplMeshName() {
        return new SupplMeshName();
    }

    /**
     * Create an instance of {@link parsers.medline.MeshHeading }
     *
     */
    public MeshHeading createMeshHeading() {
        return new MeshHeading();
    }

    /**
     * Create an instance of {@link parsers.medline.Abstract }
     *
     */
    public Abstract createAbstract() {
        return new Abstract();
    }


}
